### ISSUE TITLE
YoutubePlayer.playVideoWithID 

### ISSUE THREAD

**Issue by almorak** [eaceto/react-native-youtube-player#1]
React native:0.53.0
react-native-youtube-player:0.0.2

Got error when call
YoutubePlayer.playVideoWithID("youtube-video-id", options);

Exception:
YoutubePlayer.playVideoWithID is not a function
Unhandled JS Exception: YoutubePlayer.playVideoWithID is not a function

**Comment by eaceto** [comment]
do you still have this error? I'll check it if so.

**Comment by eaceto** [comment]
Method signature has changed to
    YoutubePlayer.playVideo("youtube-video-id", options);
Please, re-read the README.md
